### PR TITLE
Sync with ESCOMP/master to bring component level PIO initialization

### PR DESCRIPTION
**Pull request by uturuncoglu**
### Description of changes
This PR aims to bring component level PIO initialization to support/HAFS

### Specific notes

Contributors other than yourself, if any: None

CMEPS Issues Fixed (include github issue #): None

Are changes expected to change answers?
 - [x] bit for bit
 - [ ] different at roundoff level
 - [ ] more substantial 

Any User Interface Changes (namelist or namelist defaults changes)?
 - [ ] Yes
 - [x] No

Testing performed:
- Full RTs are run in HAFS model level without any problem
- S2S is tested externally by Denise and it is bit-to-bit reproducable
- HAFS fully coupled application is also tested through the use of HAFS application and it was Bir-to-bit reproducible
- The available data model regression tests are run without any problem: DATM+DOCN,  DATM+HYCOM and FV3+DOCN(regional).
- CESM full test suit also run and all tests were passed

### CODE REVIEW

**Review by BinLiu-NOAA — APPROVED** [review]
Looks good.

**Comment by BinLiu-NOAA** [comment]
@uturuncoglu In order to not break the support/HAFS branch at the model level, please hold this PR so that it goes back into the support/HAFS branch together with the following PRs:
hafs-community/ufs-weather-model#8
hafs-community/CDEPS#2
hafs-community/NEMS#3

**Comment by uturuncoglu** [comment]
@BinLiu-NOAA sure. I am waiting for your approval.

**Review by danrosen25 — APPROVED** [review]
This work was approved here:
[https://github.com/ESCOMP/CMEPS/pull/158](https://github.com/ESCOMP/CMEPS/pull/158)
The rest of the changes are related to synchronizing hafs-community with the latest ESCOMP work.

**Pull request merged**
